import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // TODO: Integrasi user dari context atau localStorage jika sudah login
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        {/* <Navbar /> */}
        <div className="min-h-screen bg-white">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
